#!/usr/bin/env php
<?php
define('ROOT_PATH', __DIR__ .'/');
define('APP_PATH', ROOT_PATH. 'php_modules/');
define('PUBLIC_PATH', ROOT_PATH . '/public/');
define('MEDIA_PATH', PUBLIC_PATH. 'media/');
define('SPT_VENDOR_PATH', ROOT_PATH. 'vendor/');
define('SPT_STORAGE_PATH', ROOT_PATH. 'storage/');

require ROOT_PATH . 'vendor/autoload.php';
$app = new DTM\core\libraries\Cli(
    new SPT\Container\Joomla,
    PUBLIC_PATH,
    APP_PATH,
    ROOT_PATH. 'config',
    'App'
);

$app->execute();